### ISSUE TITLE
White bar appears at bottom of screen when you scroll down on mobile

### ISSUE THREAD

**Issue by emirdero** [aerohub/hugo-identity-theme#11]
Hey, I've been testing out this template and I found an issue with a white bar appearing at bottom on mobile. 
[What it should look like](https://i.imgur.com/16GskHX.png), the bar doesnt start to apear before the site is fully loaded.

[What it looks like after it has fully loaded and you scroll down](https://i.imgur.com/cMsVrAP.png)

[It apears whenever you scroll down](https://i.imgur.com/BiCdJzO.png), you can see that it is opaque 

Screenshots are from a Samsun Galaxy s7 and it has also been test on a Galaxy s4 neo with same results.
When tested on a desktop PC the bar did not apear.

**Comment by stp-ip** [comment]
What browser do you use on the mobile devices?

**Comment by emirdero** [comment]
Google chorme, sorry for late respons

**Comment by stp-ip** [comment]
Can't reproduce with my nexus 5x. Hard to debug. Will see if I can find the issue during the next iteration.

**Comment by Ketouem** [comment]
Same issue on my OnePlus One (Google Chrome).

**Comment by stp-ip** [comment]
Will take another stab at reproducing and debugging. No ETA.

**Comment by stp-ip** [comment]
Was a bit more annoying issue it seems. Should be fixed now. If anything comes up, open another issue.
