### ISSUE TITLE
Issue with form

### ISSUE THREAD

**Issue by merdman2** [aerohub/hugo-identity-theme#14]
Hi. I have an issue with the contact form. The submit button is most of the time disabled. I haven't figured out when it is enabled. But even then it doesn't submit. I looked at it for a long time, but I'm lost where it might be broken. Just thought you might want to know.

**Comment by thomaslazar** [comment]
i have a similar issue. the interesting thing is... i can click the disabled button and get the emails. but the notifications that it worked or didn't work are not showing up i guess because the button is disabled.

**Comment by stp-ip** [comment]
It should get activated, when all form data is validated. Are any of you using a script blocker or so?
