### ISSUE TITLE
Template for Google Analytics does not exist.

### ISSUE THREAD

**Issue by hinderaker** [aerohub/hugo-identity-theme#2]
Line 81 in /themes/hugo-identity-theme/layouts/index.html reads as follows;
`{{ template "_internal/google_analytics.html" . }}`

That item does not exist and therefor Google Analytics is not working as intended despite the insertion of UA-key in config.

**Comment by aerohub** [comment]
Hi, @hinderaker ! That template is prebuilt internal part of Hugo package. [Here](https://gohugo.io/extras/analytics#configuring-google-analytics) is what I mean. What version of Hugo do you use?

**Comment by hinderaker** [comment]
I didn't know that, thanks :)

Hugo 0.15 according to the [Docker](https://github.com/docker/docker) image [publysher/hugo](https://github.com/publysher/docker-hugo).

**Comment by aerohub** [comment]
Serve your identity page with Hugo and look at its source code. Is there GA code?

**Comment by hinderaker** [comment]
There is indeed. So problem is not related to your theme.

**Comment by aerohub** [comment]
OK, welcome :)
