### ISSUE TITLE
How can I make the  positio  linefeed if it's too lang.

### ISSUE THREAD

**Issue by iuen** [aerohub/hugo-identity-theme#3]
I tried '/n' '/r' but it doesn't,can you help me?

**Comment by aerohub** [comment]
Hi, @iuen. The strings don't run through the Markdown processor. May be I will add this feature later. Now you may use `<br>` instead of `\n` or `\r` in `config.toml` like this:

```
# Personal settings

    name = "Jane Doe"
    position = "Senior Psychonautics Engineer<br> With Very Big Ambitions"
```

**UPDATE:** It's true for Identity theme now, not for all Hugo themes:

> The strings don't run through the Markdown processor
