### ISSUE TITLE
fa rendering

### ISSUE THREAD

**Issue by tashley** [aerohub/hugo-identity-theme#6]
I apologize, this would probably be an easy fix if I would take the time to learn HTML and CSS, but right now, I'd just like to get my site up and running.  Everything works, except the fontawesome icons show up as squares on the deployed website.  They render correctly when I host my website locally with "hugo server" at localhost:1313.  I have copied all of the contents from the document root on my server.

https://www.tcashley.com/

Thanks!

**Comment by aerohub** [comment]
Hello, @tashley! 
I think it's not a problem of HTML or CSS. It looks like problem with [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). This is what I see in developer's inspector when visit https://www.tcashley.com/ (with WWW):

<pre>Font from origin 'https://tcashley.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.tcashley.com' is therefore not allowed access.</pre>

When we visit https://tcashley.com/ (without WWW) we'll see that all works fine.

**Comment by aerohub** [comment]
@tashley As for solution... If you plan to use nothing but a subdomain (with WWW), try to generate a site with 

```
# Site settings
baseurl = "https://www.tcashley.com" #without ending slash
languageCode = "en-us"
theme = "hugo-identity-theme"
```

in your config.toml

Or use link anywhere without WWW. If you need both adressess you need consult with your hosting support or anybody else from community. Alas, I am not cool in it.

**Comment by tashley** [comment]
@aerohub Thanks so much! I really appreciated it.  Such a simple fix but I had spent way too long trying to figure that out.

**Comment by aerohub** [comment]
Glad it was useful. Thank you for using the theme :)
